name: batch build and test

on:
  push:
    branches: [ "main" ,"develop" ]
# PRでのCI実行は必要であれば行う
#  pull_request:
#    branches: [ "main", "develop" ]

# TODO 規模拡大した場合はキャッシュを入れる
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: cd batch && yarn install
      - env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: cd batch && yarn test
